### ISSUE TITLE
Add Tableland network to domain allowlist until CID's CSP metatag can be honored

### ISSUE THREAD

**Issue by awmuncy** [web3-storage/w3link#34]
In issue #27, some domains were added to the CSP. It seems like it is mostly other IPFS gateways, though I noticed `https://*.githubusercontent.com` in there too. 

Can we get `tableland.network` and `*.tableland.network` added to that list?

We're excited about the solution offered [here](https://github.com/web3-storage/w3link/issues/27#issuecomment-1343458723) but in the short term we'd like folks to be able to use w3s.link for any applications using tableland.

**Comment by awmuncy** [comment]
@vasco-santos

**Comment by vasco-santos** [comment]
Thanks for raising new issue @awmuncy 

Just submitted a PR and will release this right away
