### ISSUE TITLE
Slow file download in large CARs

### ISSUE THREAD

**Issue by leszko** [web3-storage/w3link#46]
When a CAR with a large number of files is uploaded then, downloading a single file is very slow.

In the Livepeer scenario, when we uploaded a CAR with a segmented 2h video, it's not possible to play it back in any player like HLS Player.

-----------------------------

**Steps to reproduce**

1. Here is a w3s link to the uploaded video manifest file: https://bafybeie4p7u2fw4zvmqnivgdwpet2ddyqex6o3gfzlppjjzgerbpilau5u.ipfs.w3s.link/index.m3u8

It's not possible to play it back in [HLS Player](https://www.hlsplayer.net/#type=m3u8&src=https%3A%2F%2Fbafybeie4p7u2fw4zvmqnivgdwpet2ddyqex6o3gfzlppjjzgerbpilau5u.ipfs.w3s.link%2Findex.m3u8). The next steps explain why.

2. When you try to download this file (`350B`), it takes ~ `21s`

```
$ time wget -q https://bafybeie4p7u2fw4zvmqnivgdwpet2ddyqex6o3gfzlppjjzgerbpilau5u.ipfs.w3s.link/index.m3u8

real	0m21.228s
```

If you try the same command the second time, it's fast.

3. We can try to download the next file HLS Player would like to download.

```
$ cat index.m3u8 | grep m3u8
indexlow-bitrate.m3u8
index720p0.m3u8

$ time wget -q https://bafybeie4p7u2fw4zvmqnivgdwpet2ddyqex6o3gfzlppjjzgerbpilau5u.ipfs.w3s.link/indexlow-bitrate.m3u8

real	0m22.368s
```

Again it's very slow.

4. We can try to download the next file HLS Player will try to download.

```
$ cat indexlow-bitrate.m3u8 | grep '.ts' | head -3
indexlow-bitrate_00001.ts
indexlow-bitrate_00002.ts
indexlow-bitrate_00003.ts

$ time wget -q https://bafybeie4p7u2fw4zvmqnivgdwpet2ddyqex6o3gfzlppjjzgerbpilau5u.ipfs.w3s.link/indexlow-bitrate_00002.ts

real	0m22.513s
```

Again, it's very slow.

**Comment by vasco-santos** [comment]
Hi @leszko 
When was this content uploaded into web3.storage? From what I can see, it was not uploaded to web3.storage per https://api.web3.storage/status/bafybeie4p7u2fw4zvmqnivgdwpet2ddyqex6o3gfzlppjjzgerbpilau5u

Our reads pipeline is not optimized for content that is not stored in web3.storage given we don't know where the content is beforehand. Therefore, we need to go through the public IPFS network and find the content.

**Comment by leszko** [comment]
It was uploaded to web3.storage. What we do in the Livepeer<>web3.storage integration, is the following:

1. Upload each video segment with `w3 can store add`
2. Then, create a CAR with file links pointing to the segments uploaded in Point 1
3. Upload CAR with `w3 can store upload`

The interesting thing is that for small input video files (< 100MB) everything works fine. However, when we try to upload segments for bigger input video files (resulting in more segment files in CAR), then the reads are very slow.

**Comment by vasco-santos** [comment]
@leszko ok thanks for the context. So, you are already using the new API 👍🏼 

```
curl -I https://bafybeie4p7u2fw4zvmqnivgdwpet2ddyqex6o3gfzlppjjzgerbpilau5u.ipfs.w3s.link/index.m3u8
HTTP/2 200
date: Tue, 14 Feb 2023 12:30:36 GMT
content-type: audio/x-mpegurl
content-length: 350
cf-ray: 7995d065cf4358ea-TXL
accept-ranges: bytes
access-control-allow-origin: *
cache-control: public, max-age=29030400, immutable
etag: "bafkreid3howhastd5xcqnf4m6sjorkiddannvtjwvq7skepuddern2s2bm"
strict-transport-security: max-age=31536000; includeSubDomains; preload
cf-cache-status: DYNAMIC
access-control-allow-headers: X-Requested-With, Range, Content-Range, X-Chunked-Output, X-Stream-Output
access-control-allow-methods: GET
access-control-allow-methods: GET, POST, OPTIONS
access-control-expose-headers: Link
content-security-policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data: https://*.w3s.link https://*.nftstorage.link https://*.dweb.link https://ipfs.io/ipfs/ https://*.githubusercontent.com https://tableland.network https://*.tableland.network ; form-action 'self'; navigate-to 'self'; connect-src 'self' blob: data: https://*.w3s.link https://*.nftstorage.link https://*.dweb.link https://ipfs.io/ipfs/ https://*.githubusercontent.com https://tableland.network https://*.tableland.network ; report-to csp-endpoint ; report-uri https://csp-report-to.web3.storage
reporting-endpoints: csp-endpoint="https://csp-report-to.web3.storage"
server-timing: request;dur=20530
timing-allow-origin: *
x-dotstorage-anchor: da34b390f0a08754cf5ee9293498507314f47e17c7e7310bdbc31857137af1a5
x-dotstorage-resolution-id: https://ipfs.io
x-dotstorage-resolution-layer: public-race-l1
x-ipfs-datasize: 350
x-ipfs-gateway-host: ipfs-bank7-am6
x-ipfs-lb-pop: gateway-bank1-am6
x-ipfs-path: /ipfs/bafybeie4p7u2fw4zvmqnivgdwpet2ddyqex6o3gfzlppjjzgerbpilau5u/index.m3u8
x-ipfs-pop: ipfs-bank7-am6
x-ipfs-roots: bafybeie4p7u2fw4zvmqnivgdwpet2ddyqex6o3gfzlppjjzgerbpilau5u,bafkreid3howhastd5xcqnf4m6sjorkiddannvtjwvq7skepuddern2s2bm
x-proxy-cache: MISS
server: cloudflare
```

I see that we are going through the old reads pipeline and not new one based on the `x-dotstorage-resolution-id: https://ipfs.io`. But, I can confirm now that given CID is in new API DB

**Comment by heyjay44** [comment]
@leszko thank you for flagging and providing helpful details. I've prioritised this issue for review at the start of next week.

**Comment by vasco-santos** [comment]
There is over 1000 CAR files written for rebuilding this root CID. I think we are hitting a CF Workers limit while trying to get a response for this from Freeway. As a result, we need to fallback to ipfs.io because Freeway fails to retrieve this.

Next step is to reach out to Cloudflare and try to figure out what limits we are hitting and try to have those increased or change anything. I will keep you posted

**Comment by dchoi27** [comment]
How was the video uploaded @leszko ? Using the web3.storage upload API or the new w3up API? (context is that w3up can handle larger CAR files, so you need to chunk a file into fewer pieces)

**Comment by leszko** [comment]
> How was the video uploaded @leszko ? Using the web3.storage upload API or the new w3up API? (context is that w3up can handle larger CAR files, so you need to chunk a file into fewer pieces)

I used w3up API and with the `w3` CLI executing the following commands:
- `w3 can store add` - to upload every single file
- `w3 can store upload` to CAR structure pointing to the uploaded files

**Comment by leszko** [comment]
I think for the HLS video it's not that unusual that there are so many files (each uploaded as a separate CAR). In HLS each video segment is a separate file. Segments are 1-10s (recommended 6s), so a video of 2h would have 1200 segments = 1200 files = 1200 CARs.

**Comment by dchoi27** [comment]
@vasco-santos would there be an easy way to put multiple CAR files together into a single CAR while preserving the multiple root content CIDs? if CARs are just serialized blocks, it feels like it should be easy enough to get the 1200 CARs down to a lower number...

**Comment by leszko** [comment]
@vasco-santos any thoughts on that?

**Comment by olizilla** [comment]
As an experiment, are you able to change the m3u8 so that it links out to a separate CID root for each chunk? You'd need to call `w3 up` each chunk, and then compose the m3u8 with absolute urls, for each 6s video chunk root.

This would mean that each root has a small amount of data, and should give you similar perf for a large file to the smaller video files tests you've done. We're hitting a sub-resource request limit in cloudflare, and we're working on getting it lifted, and also figuring out what we can change, but in the meantime this might help!

**Comment by leszko** [comment]
Thanks for the suggestion. Using absolute paths in the `m3u8` manifest file should work. Though, I think it's a kind of workaround, so not sure if we want to implement it right now or wait until you solve the issue with cloudflare.

**Comment by olizilla** [comment]
Oh yes, it's a workaround. It would all still be content-addressed though! if a content-addressed m3u lists content addressed chunks, it's all good! I know it doesn't look as neat as if it's all under a single root, but the magic of content-addressing means that shouldn't matter in practice.

So far CF have not given any signal that they would lift the limit, and a proper solution for this in our side will be a few weeks out.

**Comment by olizilla** [comment]
also of note, the js client and cli defaults aim to pack 100MiB per CAR shard. If you can `store/add` multiple video sections in a batches to pack them closer to 100MiBs each, that would mitigate the issue you're hitting.
