### ISSUE TITLE
Range request response returning 200 instead of 206

### ISSUE THREAD

**Issue by ikreymer** [web3-storage/w3link#9]
It looks like the range request is actually working, includes correct `content-range` and `content-length` headers,
but the status code is a 200 instead of a 206.
Hopefully a quick fix!

Ex:
```
curl -v -r 10-20 "https://bafybeih43vjosti3zf4hvob3bwms4myqyic3ljywjhsof6rf3uhzwtorgu.ipfs.w3s.link/webarchive.wacz
```

**Comment by vasco-santos** [comment]
This is closed by https://github.com/web3-storage/reads/releases/tag/edge-gateway-v1.0.4

**Comment by vasco-santos** [comment]
@ikreymer confirmed this is fixed by new release
